export const productos = [
    {
        categoriaId: 1,
        categoriaNombre: 'Anillos',
        id: 1,
        title: "Anillo 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dignissim augue viverra commodo lacinia. Nulla",
        descriptionLong: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et nisl et lectus fermentum aliquam. Nullam sit amet est ut arcu venenatis tempor. Ut elementum molestie tortor at sodales. Nunc accumsan velit eget felis efficitur posuere. Sed condimentum eu libero vitae venenatis. Donec ut aliquam augue. Sed molestie est a ipsum luctus eleifend. Mauris id fermentum elit. Morbi elementum varius porttitor. Etiam eget tempus enim, elementum cursus risus. Aliquam et viverra velit, sit amet fermentum purus. Etiam et justo non elit imperdiet malesuada. Phasellus vehicula erat a orci eleifend condimentum. Phasellus et tincidunt velit. Morbi tincidunt vestibulum rutrum.",
        price: "25",
        stock: 10,
        url: "https://picsum.photos/200?random=9",
        img: "https://picsum.photos/600?random=9",
    },
    {
        categoriaId: 1,
        categoriaNombre: 'Anillos',
        id: 2,
        title: "Anillo 2",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dignissim augue viverra commodo lacinia. Nulla",
        descriptionLong: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et nisl et lectus fermentum aliquam. Nullam sit amet est ut arcu venenatis tempor. Ut elementum molestie tortor at sodales. Nunc accumsan velit eget felis efficitur posuere. Sed condimentum eu libero vitae venenatis. Donec ut aliquam augue. Sed molestie est a ipsum luctus eleifend. Mauris id fermentum elit. Morbi elementum varius porttitor. Etiam eget tempus enim, elementum cursus risus. Aliquam et viverra velit, sit amet fermentum purus. Etiam et justo non elit imperdiet malesuada. Phasellus vehicula erat a orci eleifend condimentum. Phasellus et tincidunt velit. Morbi tincidunt vestibulum rutrum.",
        price: "50",
        stock: 2,
        img: "https://picsum.photos/600?random10",
        url: "https://picsum.photos/200?random=10"
    },
    {
        categoriaId: 1,
        categoriaNombre: 'Anillos',
        id: 3,
        title: "Anillo 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dignissim augue viverra commodo lacinia. Nulla",
        descriptionLong: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et nisl et lectus fermentum aliquam. Nullam sit amet est ut arcu venenatis tempor. Ut elementum molestie tortor at sodales. Nunc accumsan velit eget felis efficitur posuere. Sed condimentum eu libero vitae venenatis. Donec ut aliquam augue. Sed molestie est a ipsum luctus eleifend. Mauris id fermentum elit. Morbi elementum varius porttitor. Etiam eget tempus enim, elementum cursus risus. Aliquam et viverra velit, sit amet fermentum purus. Etiam et justo non elit imperdiet malesuada. Phasellus vehicula erat a orci eleifend condimentum. Phasellus et tincidunt velit. Morbi tincidunt vestibulum rutrum.",
        price: "75",
        stock: 0,
        img: "https://picsum.photos/600?random=11",
        url: "https://picsum.photos/200?random=11"
    },
    {
        categoriaId: 1,
        categoriaNombre: 'Anillos',
        id: 4,
        title: "Anillo 4",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dignissim augue viverra commodo lacinia. Nulla",
        descriptionLong: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et nisl et lectus fermentum aliquam. Nullam sit amet est ut arcu venenatis tempor. Ut elementum molestie tortor at sodales. Nunc accumsan velit eget felis efficitur posuere. Sed condimentum eu libero vitae venenatis. Donec ut aliquam augue. Sed molestie est a ipsum luctus eleifend. Mauris id fermentum elit. Morbi elementum varius porttitor. Etiam eget tempus enim, elementum cursus risus. Aliquam et viverra velit, sit amet fermentum purus. Etiam et justo non elit imperdiet malesuada. Phasellus vehicula erat a orci eleifend condimentum. Phasellus et tincidunt velit. Morbi tincidunt vestibulum rutrum.",
        price: "100",
        stock: 20,
        img: "https://picsum.photos/600?random=12",
        url: "https://picsum.photos/200?random=12"
    },
    {
        categoriaId: 2,
        categoriaNombre: 'Pulseras',
        id: 9,
        title: "Pulsera 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dignissim augue viverra commodo lacinia. Nulla",
        descriptionLong: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et nisl et lectus fermentum aliquam. Nullam sit amet est ut arcu venenatis tempor. Ut elementum molestie tortor at sodales. Nunc accumsan velit eget felis efficitur posuere. Sed condimentum eu libero vitae venenatis. Donec ut aliquam augue. Sed molestie est a ipsum luctus eleifend. Mauris id fermentum elit. Morbi elementum varius porttitor. Etiam eget tempus enim, elementum cursus risus. Aliquam et viverra velit, sit amet fermentum purus. Etiam et justo non elit imperdiet malesuada. Phasellus vehicula erat a orci eleifend condimentum. Phasellus et tincidunt velit. Morbi tincidunt vestibulum rutrum.",
        price: "25",
        stock: 10,
        img: "https://picsum.photos/600?random=1",
        url: "https://picsum.photos/200?random=1"
    },
    {
        categoriaId: 2,
        categoriaNombre: 'Pulseras',
        id: 10,
        title: "Pulsera 2",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dignissim augue viverra commodo lacinia. Nulla",
        descriptionLong: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et nisl et lectus fermentum aliquam. Nullam sit amet est ut arcu venenatis tempor. Ut elementum molestie tortor at sodales. Nunc accumsan velit eget felis efficitur posuere. Sed condimentum eu libero vitae venenatis. Donec ut aliquam augue. Sed molestie est a ipsum luctus eleifend. Mauris id fermentum elit. Morbi elementum varius porttitor. Etiam eget tempus enim, elementum cursus risus. Aliquam et viverra velit, sit amet fermentum purus. Etiam et justo non elit imperdiet malesuada. Phasellus vehicula erat a orci eleifend condimentum. Phasellus et tincidunt velit. Morbi tincidunt vestibulum rutrum.",
        price: "50",
        stock: 2,
        img: "https://picsum.photos/600?random=2",
        url: "https://picsum.photos/200?random=2"
    },
    {
        categoriaId: 2,
        categoriaNombre: 'Pulseras',
        id: 11,
        title: "Pulsera 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dignissim augue viverra commodo lacinia. Nulla",
        descriptionLong: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et nisl et lectus fermentum aliquam. Nullam sit amet est ut arcu venenatis tempor. Ut elementum molestie tortor at sodales. Nunc accumsan velit eget felis efficitur posuere. Sed condimentum eu libero vitae venenatis. Donec ut aliquam augue. Sed molestie est a ipsum luctus eleifend. Mauris id fermentum elit. Morbi elementum varius porttitor. Etiam eget tempus enim, elementum cursus risus. Aliquam et viverra velit, sit amet fermentum purus. Etiam et justo non elit imperdiet malesuada. Phasellus vehicula erat a orci eleifend condimentum. Phasellus et tincidunt velit. Morbi tincidunt vestibulum rutrum.",
        price: "75",
        stock: 0,
        img: "https://picsum.photos/600?random=3",
        url: "https://picsum.photos/200?random=3"
    },
    {
        categoriaId: 2,
        categoriaNombre: 'Pulseras',
        id: 12,
        title: "Pulsera 4",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dignissim augue viverra commodo lacinia. Nulla",
        descriptionLong: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et nisl et lectus fermentum aliquam. Nullam sit amet est ut arcu venenatis tempor. Ut elementum molestie tortor at sodales. Nunc accumsan velit eget felis efficitur posuere. Sed condimentum eu libero vitae venenatis. Donec ut aliquam augue. Sed molestie est a ipsum luctus eleifend. Mauris id fermentum elit. Morbi elementum varius porttitor. Etiam eget tempus enim, elementum cursus risus. Aliquam et viverra velit, sit amet fermentum purus. Etiam et justo non elit imperdiet malesuada. Phasellus vehicula erat a orci eleifend condimentum. Phasellus et tincidunt velit. Morbi tincidunt vestibulum rutrum.",
        price: "100",
        stock: 20,
        img: "https://picsum.photos/600?random=4",
        url: "https://picsum.photos/200?random=4"
    },
    {
        categoriaId: 2,
        categoriaNombre: 'Pulseras',
        id: 5,
        title: "Pulsera 5",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dignissim augue viverra commodo lacinia. Nulla",
        descriptionLong: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et nisl et lectus fermentum aliquam. Nullam sit amet est ut arcu venenatis tempor. Ut elementum molestie tortor at sodales. Nunc accumsan velit eget felis efficitur posuere. Sed condimentum eu libero vitae venenatis. Donec ut aliquam augue. Sed molestie est a ipsum luctus eleifend. Mauris id fermentum elit. Morbi elementum varius porttitor. Etiam eget tempus enim, elementum cursus risus. Aliquam et viverra velit, sit amet fermentum purus. Etiam et justo non elit imperdiet malesuada. Phasellus vehicula erat a orci eleifend condimentum. Phasellus et tincidunt velit. Morbi tincidunt vestibulum rutrum.",
        price: "25",
        stock: 10,
        img: "https://picsum.photos/600?random=5",
        url: "https://picsum.photos/200?random=5"
    },
    {
        categoriaId: 2,
        categoriaNombre: 'Pulseras',
        id: 6,
        title: "Pulsera 6",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dignissim augue viverra commodo lacinia. Nulla",
        descriptionLong: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et nisl et lectus fermentum aliquam. Nullam sit amet est ut arcu venenatis tempor. Ut elementum molestie tortor at sodales. Nunc accumsan velit eget felis efficitur posuere. Sed condimentum eu libero vitae venenatis. Donec ut aliquam augue. Sed molestie est a ipsum luctus eleifend. Mauris id fermentum elit. Morbi elementum varius porttitor. Etiam eget tempus enim, elementum cursus risus. Aliquam et viverra velit, sit amet fermentum purus. Etiam et justo non elit imperdiet malesuada. Phasellus vehicula erat a orci eleifend condimentum. Phasellus et tincidunt velit. Morbi tincidunt vestibulum rutrum.",
        price: "50",
        stock: 2,
        img: "https://picsum.photos/600?random=6",
        url: "https://picsum.photos/200?random=6"
    },
    {
        categoriaId: 2,
        categoriaNombre: 'Pulseras',
        id: 7,
        title: "Pulsera 7",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dignissim augue viverra commodo lacinia. Nulla",
        descriptionLong: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et nisl et lectus fermentum aliquam. Nullam sit amet est ut arcu venenatis tempor. Ut elementum molestie tortor at sodales. Nunc accumsan velit eget felis efficitur posuere. Sed condimentum eu libero vitae venenatis. Donec ut aliquam augue. Sed molestie est a ipsum luctus eleifend. Mauris id fermentum elit. Morbi elementum varius porttitor. Etiam eget tempus enim, elementum cursus risus. Aliquam et viverra velit, sit amet fermentum purus. Etiam et justo non elit imperdiet malesuada. Phasellus vehicula erat a orci eleifend condimentum. Phasellus et tincidunt velit. Morbi tincidunt vestibulum rutrum.",
        price: "75",
        stock: 0,
        img: "https://picsum.photos/600?random=7",
        url: "https://picsum.photos/200?random=7"
    },
    {
        categoriaId: 2,
        categoriaNombre: 'Pulseras',
        id: 8,
        title: "Pulsera 8",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dignissim augue viverra commodo lacinia. Nulla",
        descriptionLong: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et nisl et lectus fermentum aliquam. Nullam sit amet est ut arcu venenatis tempor. Ut elementum molestie tortor at sodales. Nunc accumsan velit eget felis efficitur posuere. Sed condimentum eu libero vitae venenatis. Donec ut aliquam augue. Sed molestie est a ipsum luctus eleifend. Mauris id fermentum elit. Morbi elementum varius porttitor. Etiam eget tempus enim, elementum cursus risus. Aliquam et viverra velit, sit amet fermentum purus. Etiam et justo non elit imperdiet malesuada. Phasellus vehicula erat a orci eleifend condimentum. Phasellus et tincidunt velit. Morbi tincidunt vestibulum rutrum.",
        price: "100",
        stock: 20,
        img: "https://picsum.photos/600?random=8",
        url: "https://picsum.photos/200?random=8"
    },
];
